const eventos = [

  {
    fecha: [{ day: "28", month:"OCTUBRE", year:"22", location: "Pepsi Center - CDMX" }],
    nombre: ["Khruangbin"],
    invitados: "invitados",
    artists: ["Pachyman"],

    id: 0,
    url: require('../assets/khrung.jpg'),
  },
  {
    fecha: [{ day: "29", month:"OCTUBRE", year:"22", location: "BAR ORIENTE - CDMX" }],
    nombre: ["METRONOMY"],
    invitados: 'invitados',
    artists: ["Pan amSTERDAM"],
    id: 1,
    url: require('../assets/metro.jpg'),
  },
  {
    fecha: [
      { day: "28", month:"octubre", year:"22", location: "Auditorio Pabellon M - MTY" },
      { day: "31", month:"octubre", year:'22', location: "Teatro Diana - GDL" },
      { day: "02", month:"noviembre", year:"22", location: "Pepsi center wtc - CDMX" },
    ],
    nombre: ["BEACH HOUSE"],
    artists: ["Estereomance"],
    invitados: "invitados",
    id: 2,
    url: require('../assets/beach.jpg'),
    buy: "",
  },
  {
    fecha: [
      { day: "09", month:"NOVIEMBRE", year:"22", location: "Miller - CDMX" },
      { day: "10", month:"NOVIEMBRE", year:"22", location: "Miller - CDMX" },
    ],
    invitados:null,
    nombre:[ "FATBOY SLIM"],
    id: 3,
    url: require('../assets/fatboy.jpg'),
  },
  {
    fecha: [{day:"10", month:'NOVIEMBRE', year:'22',  location: "BAR ORIENTE- CDMX"}],
    nombre: ["HERENCIA DE PATRONES"],
    id: 4,
    url: require('../assets/herencia.webp'),
  },
  {
    fecha: [{day:'16', month:'NOVIEMBRE', year:22, location: "Palacio de los deportes - CDMX"},{day:'17', month:'NOVIEMBRE', year:22, location: "Palacio de los deportes - CDMX"}],
    nombre:[ "C TANGANA"],
    id: 5,
    url: require('../assets/ctangana.jpg'),
  },
  {
    fecha: [{day:'19', month:'NOVIEMBRE', year:'22', location:'GUANAMOR TEATRO - GDL' },{day:'24', month:'NOVIEMBRE', year:'22', location:'Auditorio BB - CDMX'}],
    nombre: ["NICKI NICOLE"],
    
    id: 6,
    url: require('../assets/nicki.jpg'),
  },
  {
    fecha: [{day:"26", month:"NOVIEMBRE", year:"22",location: "Funk club - CDMX"}],
    nombre: ["THE BLAZE"],
    info: "",
    id: 7,
    url: require('../assets/blaze.jpg'),
  },
  {
    fecha: [{day:"09",month:"DICIEMBRE", year:"22", location:"Acapulco - gro"},{day:"10", month:"DICIEMBRE", year:"22", location:"Acapulco - gro"},{day:"11", month:"DICIEMBRE", year:"22", location:"Acapulco - gro"}],
    nombre: ["TRÓPICO"],
    info: "",
    artists:["THE WHITEST BOY ALIVE",
  'Röyksopp',
  'os mutantes',
  'dj harvey',
  'la femme',
  'myd',
  'tsha',
  'charlotte adigery ',
  ' & bolis pupul',
  'lewis ofman',
  'bora uzer',
  'weval',
  'nick hakim',
  'vegyn',
  'jenia tarsol',
  'chloé caillet',
  'ghetto kids',
  'girl ultra',
  'robot95',
  'yosoymatt',
  'meridian brothers',
  'voilaa',
  'vanessa zamora',
  'felipe gordon',
  'sonido gallo negro',
  'son rompe pera',
  'petite amie',
  'tornado wallace',
  'tonga conga',
  'florentino',
  'julian lamadrid',
  'alise teilz',
  'glass cristina',
  'los eclipses',
  'victoria volkova',
  'sinopoli & maccabi',
  'nash','paraiso beat',
  'alejandro veneno',
  'esquivel',
  'discosis',
  'sooscaveman',
  'cami laye okun',
  'rush davis',
  'cachirula',
  'isaac ferry',
  'pirate stereo',
'miguel alanis',
'ritmonzon',
'miss mara',
'hofi kofi',
'moar',
'america fendi',
'steven guberek',
'shakes + tv & amigos'
  ],
    id: 8,
    url: require('../assets/tropico.jpg'),
  },
  {
    fecha: [{ day: "01", month:"ABRIL", year:"23", location: "Parque Bicentenario - CDMX" },{ day: "02", month:"ABRIL", year:"23", location: "Parque Bicentenario - CDMX" }],
    nombre: ["CEREMONIA"],
    artists: [
      "Travis Scott",
      "m.i.a",
      "jamie xx",
      "Fred Again..",
      "Moderat",
      "Tokischas",
      "Julieta Venegas",
      'L`IMPéRATRICE',
      'Willow',
      'Honey Dijon','junior h',
      'trueno',
      'villano antillano',
      'eme malafe',
      'tr/st',
      'roju',
      'Tayhana',
      'DOMI & JD BECK',
      'USTED SEñalamelo',
      'louta',
      'taichu',
      'avalon emerson',
      'opium g', 
      'Nsqk',
      'la goony chonga',
      'zizy',
      'etheil cain',
      'el malilla',
      'lsdxoxo',
      'friolento',
      'rebe',
      'crystallmess',
      'zemmoa',
      'rubio',
      'go golden junk',
      'yoshi',
      'mehro',
      'meth math',
      'grls',
      'dj guapis',
      'foudeqush',
      'cuah'
    ],

    info: "",

    id: 9,
    url: require('../assets/cere-01.jpeg'),
  },
];

export default eventos;
